### ISSUE TITLE
Can't build the project, vite error

### ISSUE THREAD

**Issue by Oni07R** [cdmoro/bootstrap-vue-3#321]
I forked the project to test some fixes to a current BToast issue but I am having issues bulding it, which is kinda unexpected.
I just run `npm install` (which I see is converted to `prepare` script)

```
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> bootstrap-vue-3@0.1.7 prepare D:\Projects\bootstrap-vue-3
> husky install && vite build

husky - Git hooks installed
vite v2.8.6 building for production...
✓ 11 modules transformed.
[vite]: Rollup failed to resolve import "bootstrap/js/dist/alert" from "src/components/BAlert.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "bootstrap/js/dist/alert" from "src/components/BAlert.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (D:\Projects\bootstrap-vue-3\node_modules\vite\dist\node\chunks\dep-9c153816.js:39242:19)
    at onwarn (D:\Projects\bootstrap-vue-3\node_modules\vite\dist\node\chunks\dep-9c153816.js:39020:13)
    at Object.onwarn (D:\Projects\bootstrap-vue-3\node_modules\rollup\dist\shared\rollup.js:23129:13)
    at ModuleLoader.handleResolveId (D:\Projects\bootstrap-vue-3\node_modules\rollup\dist\shared\rollup.js:22419:26)
    at D:\Projects\bootstrap-vue-3\node_modules\rollup\dist\shared\rollup.js:22380:26
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-vue-3@0.1.7 prepare: `husky install && vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-vue-3@0.1.7 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ricca\AppData\Roaming\npm-cache\_logs\2022-03-16T10_16_00_521Z-debug.log
```

Even if I try to fix the problematic import, the same error arise in another component and so on.
Am I missing something?

**Comment by mariusa** [comment]
@xvaara guess this is related to https://github.com/cdmoro/bootstrap-vue-3/pull/315 ?

**Comment by xvaara** [comment]
@Oni07R npm install doesn't install boostrap, since it's peerDepency. try npm install bootstrap

@mariusa maybe we should include it in devDepencies?

**Comment by xvaara** [comment]
@Oni07R It also seems you are using a quite old version of npm, try to upgrade that to see if it helps. 
Check if you are missing node_modules/bootstrap, to narrow down it the problem is with bootstrap missing, or importing the files.

**Comment by mariusa** [comment]
It also works for me
```

> bootstrap-vue-3@0.1.7 build
> vite build

vite v2.8.6 building for production...
✓ 222 modules transformed.
dist/bootstrap-vue-3.css     12.61 KiB / gzip: 2.76 KiB
dist/bootstrap-vue-3.es.js   463.77 KiB / gzip: 92.19 KiB
dist/bootstrap-vue-3.umd.js   240.77 KiB / gzip: 66.20 KiB
```
bootstrap is in peerDeps

**Comment by Oni07R** [comment]
> @Oni07R It also seems you are using a quite old version of npm, try to upgrade that to see if it helps. Check if you are missing node_modules/bootstrap, to narrow down it the problem is with bootstrap missing, or importing the files.

I have installed the latest npm and it's working now. Thank you for the help!
