### ISSUE TITLE
Migrating from bootstrap-vue,  received this error 

### ISSUE THREAD

**Issue by Kyriakos-Michael** [cdmoro/bootstrap-vue-3#665]
**Received the below error on the browser console:**

```
TypeError: Cannot read properties of undefined (reading 'super')
    at getVue (index.js:618:14)
    at validateModel2 (index.js:627:13)
    at Proxy.data (index.js:655:25)
    at Proxy.mergedDataFn (runtime-core.esm-bundler.js:3689:45)
    at applyOptions (runtime-core.esm-bundler.js:3384:34)
    at finishComponentSetup (runtime-core.esm-bundler.js:7310:9)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7221:9)
    at setupComponent (runtime-core.esm-bundler.js:7143:11)
    at mountComponent (runtime-core.esm-bundler.js:5495:13)
    at processComponent (runtime-core.esm-bundler.js:5470:17)
```

**Environment (please complete the following information):**
 - OS: [Macos]
 - Version [12.6]
 - Google Chrome 105

**Additional context**
Trying to test a migration from the old bootstrap-vue

The error appears multiple times on the console.

**Comment by VividLemon** [comment]
This doesn't contain enough information to be useful for me. The error message is too cryptic to be of any use.
