### ISSUE TITLE
Refresh page when developing nuxt 3 raise document not defined error

### ISSUE THREAD

**Issue by xiangnanscu** [cdmoro/bootstrap-vue-3#706]
**Describe the bug**
The nuxt page display
```

500
document is not defined

at enableDismissTrigger (./node_modules/bootstrap/dist/js/bootstrap.js:888:21)
at ./node_modules/bootstrap/dist/js/bootstrap.js:977:3
at ./node_modules/bootstrap/dist/js/bootstrap.js:7:83
at Object. (./node_modules/bootstrap/dist/js/bootstrap.js:10:3)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at ModuleWrap. (node:internal/modules/esm/translators:190:29)
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
```

**To Reproduce**
just refresh page

**Expected behavior**
not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/8246344/192080145-c44e6248-6eeb-4108-8fb0-32a25220cebc.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 wsl2 ubuntu 20.04]
 - Version [e.g. 0.2.6]

**Additional context**

**Comment by VividLemon** [comment]
Bootstrap v5 is not ssr friendly. Your error is pointing to a bootstrap js file.

I believe they're planning on making ssr friendly changes in an upcoming update. But since they're not ssr friendly, we do not support ssr applications
